### ISSUE TITLE
:~/bitshares-ui# npm start: webpack: Failed to compile.

### ISSUE THREAD

**Issue by mahfuj001** [bitshares/bitshares-ui#1489]
I am trying  to install bitshare-ui on ubuntu 16.04. Following the instruction: https://github.com/bitshares/bitshares-ui

Below the details log and error:

root@nyc1:~/bitshares-ui# npm start

> www@2.0.180418-b start /root/bitshares-ui
> cross-env NODE_ENV=development node server.js

Listening at http://localhost:8080/ or https://localhost:8085/
webpack built 114cd98037f8e7a95df4 in 13099ms
Hash: 114cd98037f8e7a95df4
Version: webpack 2.7.0
Time: 13099ms
                            Asset       Size  Chunks  Chunk Names
           asset-symbols/icoo.png    6.48 kB
   64cfad394093dc92c9e8.worker.js    1.69 MB
                   locale-de.json      55 kB
                   locale-en.json    93.7 kB
                   locale-es.json    90.9 kB
                   locale-fr.json    34.5 kB
                   locale-it.json    85.8 kB
                   locale-ja.json     110 kB
                   locale-ko.json    45.5 kB
                   locale-ru.json     143 kB
                   locale-tr.json    73.8 kB
                   locale-zh.json      83 kB
            asset-symbols/atn.png    6.64 kB
           asset-symbols/bkbt.png    8.33 kB
            asset-symbols/bkt.png    7.64 kB
       asset-symbols/blockpay.png    10.6 kB
            asset-symbols/btc.png    5.63 kB
            asset-symbols/btm.png    2.02 kB
            asset-symbols/bto.png    23.8 kB
            asset-symbols/bts.png    3.03 kB
           asset-symbols/btsr.png    7.03 kB
          asset-symbols/btwty.png    10.5 kB
            asset-symbols/cny.png    5.98 kB
            asset-symbols/dao.png    3.64 kB
           asset-symbols/dash.png    7.19 kB
            asset-symbols/dct.png    6.51 kB
            asset-symbols/dgd.png    12.1 kB
            asset-symbols/dht.png    6.31 kB
           asset-symbols/egem.png    5.13 kB
            asset-symbols/eos.png    10.8 kB
            asset-symbols/eth.png    5.01 kB
            asset-symbols/eur.png    5.62 kB
           asset-symbols/eurt.png    3.78 kB
           asset-symbols/game.png    7.96 kB
            asset-symbols/gas.png    6.62 kB
            asset-symbols/gbg.png    6.14 kB
       asset-symbols/gdex.btc.png    6.17 kB
           asset-symbols/gold.png    6.21 kB
          asset-symbols/golos.png    7.62 kB
            asset-symbols/grc.png    9.38 kB
            asset-symbols/gxs.png    5.61 kB
      asset-symbols/hempsweet.png    16.6 kB
           asset-symbols/hero.png    29.1 kB
   3057a531e35c7dadaba1.worker.js    1.23 MB
          asset-symbols/incnt.png    9.73 kB
        asset-symbols/kexcoin.png      19 kB
            asset-symbols/krm.png    7.05 kB
           asset-symbols/lisk.png    20.1 kB
            asset-symbols/mkr.png     3.9 kB
           asset-symbols/muse.png      11 kB
            asset-symbols/neo.png    5.67 kB
            asset-symbols/nxc.png    24.7 kB
          asset-symbols/obits.png    5.04 kB
            asset-symbols/oct.png    5.06 kB
       asset-symbols/open.btc.png    6.17 kB
      asset-symbols/peerplays.png    16.6 kB
            asset-symbols/ppy.png    12.5 kB
           asset-symbols/qtum.png      10 kB
          asset-symbols/ruble.png    5.66 kB
            asset-symbols/scr.png    4.13 kB
          asset-symbols/smoke.png    13.5 kB
        asset-symbols/stealth.png    5.39 kB
          asset-symbols/steem.png    3.73 kB
             asset-symbols/tt.png    6.63 kB
            asset-symbols/usd.png    5.96 kB
           asset-symbols/usdt.png    3.78 kB
          asset-symbols/yoyow.png    15.8 kB
           asset-symbols/zeph.png     8.4 kB
        asset-symbols/kapital.png    7.64 kB
         asset-symbols/silver.png     5.2 kB
bts_genesiskeys_bloom_3cee441.dat    1.05 MB
                  dictionary.json     348 kB
                      favicon.ico    1.52 kB
                       index.html    1.36 kB
         language-dropdown/EN.png  323 bytes
         language-dropdown/KO.png     1.9 kB
         language-dropdown/DE.png  168 bytes
         language-dropdown/ES.png  996 bytes
         language-dropdown/FR.png  175 bytes
         language-dropdown/IT.png  175 bytes
         language-dropdown/JA.png  463 bytes
         language-dropdown/RU.png  164 bytes
         language-dropdown/TR.png  624 bytes
         language-dropdown/ZH.png  745 bytes
                             0.js     186 kB       0
                           app.js    13.7 MB       1  app
chunk    {0} 0.js 176 kB {1} [rendered]
  [800] ./~/intl/index.js 574 bytes {0} [built]
 [2219] ./app/assets/intl-data/en.json 3.25 kB {0} [built]
 [2220] ./~/intl/lib/core.js 173 kB {0} [built]
 [2221] ./locale-data/complete.js (ignored) 15 bytes {0}
chunk    {1} app.js (app) 10.6 MB [entry] [rendered]
  [151] (webpack)/buildin/module.js 517 bytes {1} [built]
  [492] ./app/index-dev.js 1.41 kB {1} [built]
  [798] ./app/Main-dev.js 427 bytes {1} [built]
  [799] ./~/webpack-hot-middleware/client.js 7.72 kB {1} [built]
  [960] ./app/assets/loader-dev.js 1.23 kB {1} [built]
  [962] ./app/components/Utility/Prototypes.js 866 bytes {1} [built]
 [1348] ./~/file-loader?name=dictionary.json!./app/lib/common/dictionary_en.json 61 bytes {1} [built]
 [1349] ./~/file-loader?name=favicon.ico!./app/assets/favicon.ico 57 bytes {1} [built]
 [1350] ./~/file-loader?name=index.html!./app/assets/index-dev.html 56 bytes {1} [built]
 [1380] ./~/html-entities/index.js 231 bytes {1} [built]
 [2014] ./~/strip-ansi/index.js 161 bytes {1} [built]
 [2118] ./~/webpack-hot-middleware/client-overlay.js 2.21 kB {1} [built]
 [2119] ./~/webpack-hot-middleware/process-update.js 4.33 kB {1} [built]
 [2120] ./~/whatwg-fetch/fetch.js 13 kB {1} [built]
 [2218] multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js 52 bytes {1} [built]
     + 2203 hidden modules

ERROR in multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js
Module not found: Error: Can't resolve 'react-hot-loader/wwebpack' in '/root/bitshares-ui'
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js

ERROR in ./~/css-loader!./~/postcss-loader?{"plugins":[null]}!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded"}!./app/assets/stylesheets/app.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/bitshares-ui/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/bitshares-ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
 @ ./app/assets/stylesheets/app.scss 4:14-193 13:2-17:4 14:20-199
 @ ./app/assets/loader-dev.js
 @ ./app/Main-dev.js
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js

ERROR in ./~/css-loader!./~/postcss-loader?{"plugins":[null]}!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded"}!./app/components/Explorer/witnesses.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/bitshares-ui/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/bitshares-ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
 @ ./app/components/Explorer/witnesses.scss 4:14-199 13:2-17:4 14:20-205
 @ ./app/components/Explorer/Witnesses.jsx
 @ ./app/Routes-dev.jsx
 @ ./app/index-dev.js
 @ ./app/Main-dev.js
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js

ERROR in ./~/css-loader!./~/postcss-loader?{"plugins":[null]}!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded"}!./app/components/Wallet/ImportKeys.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/bitshares-ui/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/bitshares-ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
 @ ./app/components/Wallet/ImportKeys.scss 4:14-200 13:2-17:4 14:20-206
 @ ./app/components/Wallet/ImportKeys.jsx
 @ ./app/Routes-dev.jsx
 @ ./app/index-dev.js
 @ ./app/Main-dev.js
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js

ERROR in ./~/css-loader!./~/postcss-loader?{"plugins":[null]}!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded"}!./app/components/Blockchain/json-inspector.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/bitshares-ui/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/bitshares-ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
 @ ./app/components/Blockchain/json-inspector.scss 4:14-204 13:2-17:4 14:20-210
 @ ./app/components/Explorer/Blocks.jsx
 @ ./app/components/Explorer/BlocksContainer.jsx
 @ ./app/Routes-dev.jsx
 @ ./app/index-dev.js
 @ ./app/Main-dev.js
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js

ERROR in ./~/css-loader!./~/postcss-loader?{"plugins":[null]}!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded"}!./app/components/Icon/icon.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/bitshares-ui/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/bitshares-ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
 @ ./app/components/Icon/icon.scss 4:14-194 13:2-17:4 14:20-200
 @ ./app/components/Icon/Icon.jsx
 @ ./app/components/Account/CreateAccountPassword.jsx
 @ ./app/Routes-dev.jsx
 @ ./app/index-dev.js
 @ ./app/Main-dev.js
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js

ERROR in ./~/css-loader!./~/postcss-loader?{"plugins":[null]}!./~/sass-loader/lib/loader.js?{"outputStyle":"expanded"}!./app/components/Blockchain/operations.scss
Module build failed: Error: ENOENT: no such file or directory, scandir '/root/bitshares-ui/node_modules/node-sass/vendor'
    at Error (native)
    at Object.fs.readdirSync (fs.js:961:18)
    at Object.getInstalledBinaries (/root/bitshares-ui/node_modules/node-sass/lib/extensions.js:129:13)
    at foundBinariesList (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/root/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/root/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/root/bitshares-ui/node_modules/sass-loader/lib/loader.js:3:14)
    at Module._compile (module.js:577:32)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at loadLoader (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:13:17)
    at iteratePitchingLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at iteratePitchingLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:165:10)
    at /usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:173:18
    at loadLoader (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/loadLoader.js:36:3)
    at iteratePitchingLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:169:2)
    at runLoaders (/usr/lib/node_modules/webpack/node_modules/loader-runner/lib/LoaderRunner.js:362:2)
    at NormalModule.doBuild (/usr/lib/node_modules/webpack/lib/NormalModule.js:179:3)
    at NormalModule.build (/usr/lib/node_modules/webpack/lib/NormalModule.js:268:15)
    at Compilation.buildModule (/usr/lib/node_modules/webpack/lib/Compilation.js:146:10)
    at factoryCallback (/usr/lib/node_modules/webpack/lib/Compilation.js:329:11)
    at factory (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:253:5)
    at applyPluginsAsyncWaterfall (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:99:14)
    at /usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:268:11
    at NormalModuleFactory.params.normalModuleFactory.plugin (/usr/lib/node_modules/webpack/lib/CompatibilityPlugin.js:52:5)
    at NormalModuleFactory.applyPluginsAsyncWaterfall (/usr/lib/node_modules/webpack/node_modules/tapable/lib/Tapable.js:272:13)
    at resolver (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:74:11)
    at process.nextTick (/usr/lib/node_modules/webpack/lib/NormalModuleFactory.js:205:8)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)

 @ ./app/components/Blockchain/operations.scss 4:14-200 13:2-17:4 14:20-206
 @ ./app/components/Blockchain/Operation.jsx
 @ ./app/components/Account/RecentTransactions.jsx
 @ ./app/components/Dashboard/DashboardAccountsOnly.jsx
 @ ./app/Routes-dev.jsx
 @ ./app/index-dev.js
 @ ./app/Main-dev.js
 @ multi react-hot-loader/wwebpack webpack-hot-middleware/client ./app/Main-dev.js
Child worker:
                             Asset     Size  Chunks  Chunk Names
    64cfad394093dc92c9e8.worker.js  1.69 MB       0  main
    chunk    {0} 64cfad394093dc92c9e8.worker.js (main) 1.26 MB [entry] [rendered]
       [63] ./~/bitsharesjs/es/chain/src/ChainTypes.js 2.19 kB {0} [built]
       [80] ./~/bitsharesjs/es/ecc/src/PrivateKey.js 6.17 kB {0} [built]
       [81] ./~/bitsharesjs/es/serializer/src/SerializerValidation.js 11.9 kB {0} [built]
      [113] ./~/bitsharesjs/es/ecc/src/KeyUtils.js 7.59 kB {0} [built]
      [114] ./~/bitsharesjs/es/ecc/src/address.js 2.86 kB {0} [built]
      [115] ./~/bitsharesjs/es/ecc/src/aes.js 10.4 kB {0} [built]
      [116] ./~/bitsharesjs/es/serializer/src/FastParser.js 1.89 kB {0} [built]
      [117] ./~/bitsharesjs/es/serializer/src/serializer.js 7 kB {0} [built]
      [118] ./~/bitsharesjs/es/serializer/src/types.js 31.3 kB {0} [built]
      [165] ./~/bitsharesjs/es/chain/src/ChainValidation.js 4.35 kB {0} [built]
      [166] ./~/bitsharesjs/es/chain/src/EmitterInstance.js 158 bytes {0} [built]
      [167] ./~/bitsharesjs/es/chain/src/ObjectId.js 2.08 kB {0} [built]
      [191] ./~/babel-polyfill/lib/index.js 833 bytes {0} [built]
      [192] ./~/bitsharesjs/es/index.js 1.6 kB {0} [built]
      [193] ./~/babel-loader/lib?{"compact":false,"cacheDirectory":true}!./app/lib/workers/AesWorker.js 1.62 kB {0} [built]
         + 448 hidden modules
Child worker:
                             Asset     Size  Chunks  Chunk Names
    3057a531e35c7dadaba1.worker.js  1.23 MB       0  main
    chunk    {0} 3057a531e35c7dadaba1.worker.js (main) 1.02 MB [entry] [rendered]
        [5] ./~/bitsharesjs/es/ecc/src/hash.js 1.38 kB {0} [built]
       [10] ./~/bitsharesjs/es/ecc/src/PublicKey.js 6.85 kB {0} [built]
       [14] ./~/bitsharesjs/es/chain/src/ChainTypes.js 2.19 kB {0} [built]
       [17] ./~/bitsharesjs/es/ecc/src/PrivateKey.js 6.17 kB {0} [built]
       [18] ./~/bitsharesjs/es/serializer/src/SerializerValidation.js 11.9 kB {0} [built]
       [23] ./~/bitsharesjs/es/ecc/src/KeyUtils.js 7.59 kB {0} [built]
       [24] ./~/bitsharesjs/es/ecc/src/address.js 2.86 kB {0} [built]
       [25] ./~/bitsharesjs/es/ecc/src/aes.js 10.4 kB {0} [built]
       [26] ./~/bitsharesjs/es/serializer/src/FastParser.js 1.89 kB {0} [built]
       [27] ./~/bitsharesjs/es/serializer/src/serializer.js 7 kB {0} [built]
       [67] ./~/bitsharesjs/es/index.js 1.6 kB {0} [built]
       [68] ./~/babel-loader/lib?{"compact":false,"cacheDirectory":true}!./app/lib/workers/AddressIndexWorker.js 1.42 kB {0} [built]
       [75] ./~/bitsharesjs/es/chain/src/NumberUtils.js 1.84 kB {0} [built]
       [76] ./~/bitsharesjs/es/chain/src/TransactionBuilder.js 32.4 kB {0} [built]
       [77] ./~/bitsharesjs/es/chain/src/TransactionHelper.js 3.38 kB {0} [built]
         + 122 hidden modules
webpack: Failed to compile.

Experts .... pls help

**Comment by wmbutler** [comment]
Node Version?
NPM version?

Basic troubleshooting
```
rm -rf node_modules
npm cache clean
npm i
```

**Comment by mahfuj001** [comment]
Dear Butler,
Many thanks.. for addressing ..

Node Version: v6.14.2
NPM version: 3.10.10

rm -rf node_modules --Done
npm cache clean---Done

root@nyc1:~/bitshares-ui# npm i


> husky@0.14.3 install /root/bitshares-ui/node_modules/husky
> node ./bin/install.js

module.js:478
    throw err;
    ^

Error: Cannot find module '/root/bitshares-ui/node_modules/husky/bin/install.js'
    at Function.Module._resolveFilename (module.js:476:15)
    at Function.Module._load (module.js:424:25)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)
    at bootstrap_node.js:507:3
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@~1.0.1 (node_modules/7zip-bin/node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@~2.2.0 (node_modules/7zip-bin/node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.2.0: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-mac@1.8.6 (node_modules/app-builder-bin/node_modules/app-builder-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-mac@1.8.6: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: app-builder-bin-win@1.8.6 (node_modules/app-builder-bin/node_modules/app-builder-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for app-builder-bin-win@1.8.6: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.1.2 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none was installed.
npm WARN react-qr-reader@2.1.0 requires a peer of react@~16 but none was installed.
npm WARN react-qr-reader@2.1.0 requires a peer of react-dom@~16 but none was installed.
npm WARN react-translate-component@0.14.0 requires a peer of counterpart@^0.17.0 but none was installed.
npm ERR! Linux 4.4.0-28-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "i"
npm ERR! node v6.14.2
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! husky@0.14.3 install: `node ./bin/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the husky@0.14.3 install script 'node ./bin/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the husky package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs husky
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls husky
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/bitshares-ui/npm-debug.log

Mahfuj

**Comment by wmbutler** [comment]
Possibly update node to 10.0.0 and npm 6.0?

**Comment by ggq89** [comment]
@mahfuj001 
I have the same log as mentioned above.Downgrading to npm@5.6.0 works.

`npm i -g npm@5.6.0`

solved me thanks.

**Comment by ggq89** [comment]
@mahfuj001 

I have the same log as mentioned above.Downgrading to npm@5.6.0 works.

`npm i -g npm@5.6.0`

solved my problem.
