### ISSUE TITLE
npm ERR! code ELIFECYCLE npm ERR! errno 1 npm ERR! BitShares2-light@3.1.190604-rc1 start: `cross-env NODE_ENV=development node serve` npm ERR! Exit status 1

### ISSUE THREAD

**Issue by heyasjack** [bitshares/bitshares-ui#2713]
Hello, I'm a beginner to bitshares, when I tried to run npm start in /bitshares-ui, it reported a great number of error
`

> BitShares2-light@3.1.190604-rc1 start /home/user1/bitshares-ui
> cross-env NODE_ENV=development node server.js
internal/modules/cjs/loader.js:550
    throw err;
    ^
Error: Cannot find module 'webpack'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:548:15)
    at Function.Module._load (internal/modules/cjs/loader.js:475:25)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/user1/bitshares-ui/server.js:2:15)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)

`
Here is the package.json
https://raw.githubusercontent.com/bitshares/bitshares-ui/develop/package.json

npm -v
6.9.0

node -v
v9.11.2

The first time I tried to run npm start, it showed cross-env is missed, so I install the cross-env.
I have tried npm start with no cross-env and package.json deleted cross-env, they all failed

**Comment by startailcoon** [comment]
Did you run `npm install` before you ran `npm start`?

**Comment by heyasjack** [comment]
@startailcoon yes, of course.
When I run npm install, it appeared more than ten error.

**Comment by sschiessl-bcp** [comment]
Try to separately install `npm install webpack` and report the outcome.

**Comment by heyasjack** [comment]
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/bitshares/alt.git /root/.npm/_cacache/tmp/git-clone-49f65053
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-49f65053': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T08_05_41_637Z-debug.log
root@instance-10:/home/hychen34/bitshares-ui# npm install webpack
npm ERR! code 128
npm ERR! Command failed: /usr/bin/git clone --depth=1 -q -b master https://github.com/bitshares/alt.git /root/.npm/_cacache/tmp/git-clone-e0a03ff5
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-e0a03ff5': Permission denied
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-06-02T08_10_57_270Z-debug.log

**Comment by sschiessl-bcp** [comment]
Are you accessing github with https and username/pw or with ssh and ssh key?
