### ISSUE TITLE
ERROR in ./app/assets/stylesheets/app.scss

### ISSUE THREAD

**Issue by heyasjack** [bitshares/bitshares-ui#2740]
Hello, I have some problems in npm install and npm start
npm -v
5.6.0
node -v
v9.11.2

When I connected to 0.0.0.0:8080 it reported:

> Loading...
ERROR in ./app/assets/stylesheets/app.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js??ref--11-3!./app/assets/stylesheets/app.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir '/home/user/bitshares-ui/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:921:18)
    at Object.getInstalledBinaries (/home/user/bitshares-ui/node_modules/node-sass/lib/extensions.js:131:13)
    at foundBinariesList (/home/user/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/user/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/user/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/user/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/user/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.sassLoader (/home/user/bitshares-ui/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./app/components/Icon/icon.scss (./node_modules/css-loader/dist/cjs.js!./node_modules/postcss-loader/src!./node_modules/sass-loader/lib/loader.js??ref--11-3!./app/components/Icon/icon.scss)
Module build failed (from ./node_modules/sass-loader/lib/loader.js):
Error: ENOENT: no such file or directory, scandir '/home/user/bitshares-ui/node_modules/node-sass/vendor'
    at Object.fs.readdirSync (fs.js:921:18)
    at Object.getInstalledBinaries (/home/user/bitshares-ui/node_modules/node-sass/lib/extensions.js:131:13)
    at foundBinariesList (/home/user/bitshares-ui/node_modules/node-sass/lib/errors.js:20:15)
    at foundBinaries (/home/user/bitshares-ui/node_modules/node-sass/lib/errors.js:15:5)
    at Object.module.exports.missingBinary (/home/user/bitshares-ui/node_modules/node-sass/lib/errors.js:45:5)
    at module.exports (/home/user/bitshares-ui/node_modules/node-sass/lib/binding.js:15:30)
    at Object.<anonymous> (/home/user/bitshares-ui/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.sassLoader (/home/user/bitshares-ui/node_modules/sass-loader/lib/loader.js:46:72)
ERROR in ./app/App.jsx 55:15
Module parse failed: Unexpected token (55:15)
You may need an appropriate loader to handle this file type.
| var Exchange = Loadable({
|     loader: function loader() {
>         return import( /* webpackChunkName: "exchange" */"./components/Exchange/ExchangeContainer");
|     },
|     loading: LoadingIndicator

Maybe I had make some mistake in installing npm, where it reported many error.

> 0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'start' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle BitShares2-light@3.1.190604-rc1~prestart: BitShares2-light@3.1.190604-rc1
6 silly lifecycle BitShares2-light@3.1.190604-rc1~prestart: no script for prestart, continuing
7 info lifecycle BitShares2-light@3.1.190604-rc1~start: BitShares2-light@3.1.190604-rc1
8 verbose lifecycle BitShares2-light@3.1.190604-rc1~start: unsafe-perm in lifecycle true
9 verbose lifecycle BitShares2-light@3.1.190604-rc1~start: PATH: /usr/share/npm/bin/node-gyp-bin:/home/hychen35/bitshares-ui/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
10 verbose lifecycle BitShares2-light@3.1.190604-rc1~start: CWD: /home/hychen35/bitshares-ui
11 silly lifecycle BitShares2-light@3.1.190604-rc1~start: Args: [ '-c', 'cross-env NODE_ENV=development node server.js' ]
12 info lifecycle BitShares2-light@3.1.190604-rc1~start: Failed to exec start script
13 verbose stack Error: BitShares2-light@3.1.190604-rc1 start: `cross-env NODE_ENV=development node server.js`
13 verbose stack Error: BitShares2-light@3.1.190604-rc1 start: `cross-env NODE_ENV=development node server.js`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:17:16)
13 verbose stack     at emitTwo (events.js:87:13)
13 verbose stack     at ChildProcess.emit (events.js:172:7)
13 verbose stack     at maybeClose (internal/child_process.js:821:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
14 verbose pkgid BitShares2-light@3.1.190604-rc1
15 verbose cwd /home/hychen35/bitshares-ui
16 error Linux 4.15.0-1032-gcp
17 error argv "/usr/bin/nodejs" "/usr/bin/npm" "start"
18 error node v4.2.6
19 error npm  v3.5.2
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error BitShares2-light@3.1.190604-rc1 start: `cross-env NODE_ENV=development node server.js`
24 error spawn ENOENT
25 error Failed at the BitShares2-light@3.1.190604-rc1 start script 'cross-env NODE_ENV=development node server.js'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the BitShares2-light package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     cross-env NODE_ENV=development node server.js
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs BitShares2-light
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls BitShares2-light
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

**Comment by heyasjack** [comment]
I check with `npm -v` then it reported 
npm -v
5.6.0
node -v
v9.11.2

but why did it showed in the debug report that
 2 info using npm@3.5.2
3 info using node@v4.2.6

**Comment by heyasjack** [comment]
I got it! 
I tried tried tried …… and tried.
run 
npm install or
npm i -g npm@5.6.0

**Comment by sschiessl-bcp** [comment]
Cool! So you might have had the old version user/locally installed.
