### ISSUE TITLE
error: Error: Invalid wallet name

### ISSUE THREAD

**Issue by coollen** [bitshares/bitshares-ui#3365]
I import my wallet.bin, but get error. this bin file is backup at 2018-8-29, i think it is too old.

Error loading logs from localStorage
log: Latency result:[object Object]
log: auto selecting to wss://api.bitshares.bhuz.info/ws after latency update
log: Connecting to wss://api.bitshares.bhuz.info/ws
log: synced and subscribed, chainstore ready
log: Latency result:[object Object]
error: Error: Invalid wallet name
error: Error decrypting walletError: Invalid key, could not decrypt message(2)Error: Invalid key, could not decrypt message(2)
    at Function.e.decrypt_with_checksum (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:40:173168)
    at https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:149476
    at new Promise (<anonymous>)
    at h (https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:149230)
    at https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:149151
    at new Promise (<anonymous>)
    at p (https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:149124)
    at t.Mt.restoreBackup (https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:738343)
    at t.<anonymous> (https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:738884)
    at pi (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:144:48553)
error: Error: Invalid wallet name
log: Switching to InRam storage for private session
error: Error: Invalid wallet name
error: wss://api.iamredbar.com/wsFailed to initialize with errorConnection attempt timed out after 4s
log: fallback to new url:wss://node.xbts.io/ws
log: synced and subscribed, chainstore ready
error: Error: Invalid wallet name
error: Error decrypting walletError: Invalid key, could not decrypt message(2)Error: Invalid key, could not decrypt message(2)
    at Function.e.decrypt_with_checksum (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:40:173168)
    at https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:149476
    at new Promise (<anonymous>)
    at h (https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:149230)
    at t.value (https://wallet.bitshares.org/app.bc0e47b9710cefe16a5c.js:1:383621)
    at t.handleClick (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:41:221144)
    at Object.s (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:144:457)
    at h (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:144:600)
    at https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:144:746
    at y (https://wallet.bitshares.org/vendor.69f460f031d874f0f6fc.js:144:832)
error: Error verifying wallet 钱包备份_bts_default_20180829.bininvalid_decryption_keyundefined
error: Error: Invalid wallet name

**Comment by sschiessl-bcp** [comment]
Did you rename the wallet file to 钱包备份_bts_default_20180829.bin or was it created like that?

**Comment by coollen** [comment]
it works, thx
i change the filename to all english characters, so i can get my count back, thx
