### ISSUE TITLE
Credit offer page -> sort by 'Available' => white screen

### ISSUE THREAD

**Issue by grctest** [bitshares/bitshares-ui#3578]
**Describe the bug**
Clicking the table header to sort by 'Available' results in the entire screen turning white.

**To Reproduce**
1. Go to credit offer page
2. click on the header for 'Available' to sort
3. Get white screen

**Expected behavior**
Table sorts without white screen

**Screenshots**

```
vendor.049af5c1d008aea05c6b.js:2 TypeError: Cannot read properties of undefined (reading 'toJS')
    at Object.convert_satoshi_to_typed (app.ca0591fe36ffc3c5e8fa.js:1:654721)
    at N._sortByAmount (explorer.3618f7ce2754a162d898.js:1:2244)
    at Object.sorter (explorer.3618f7ce2754a162d898.js:1:3062)
    at vendor.049af5c1d008aea05c6b.js:2:1175051
    at Array.sort (<anonymous>)
    at n.value (vendor.049af5c1d008aea05c6b.js:2:1178028)
    at n.value (vendor.049af5c1d008aea05c6b.js:2:1175836)
    at n.value (vendor.049af5c1d008aea05c6b.js:2:1175160)
    at o.renderComponent (vendor.049af5c1d008aea05c6b.js:2:1171898)
    at bs (vendor.049af5c1d008aea05c6b.js:2:3666048)
ns @ vendor.049af5c1d008aea05c6b.js:2
app.ca0591fe36ffc3c5e8fa.js:1 TypeError: Cannot read properties of undefined (reading 'toJS')
    at Object.convert_satoshi_to_typed (app.ca0591fe36ffc3c5e8fa.js:1:654721)
    at N._sortByAmount (explorer.3618f7ce2754a162d898.js:1:2244)
    at Object.sorter (explorer.3618f7ce2754a162d898.js:1:3062)
    at vendor.049af5c1d008aea05c6b.js:2:1175051
    at Array.sort (<anonymous>)
    at n.value (vendor.049af5c1d008aea05c6b.js:2:1178028)
    at n.value (vendor.049af5c1d008aea05c6b.js:2:1175836)
    at n.value (vendor.049af5c1d008aea05c6b.js:2:1175160)
    at o.renderComponent (vendor.049af5c1d008aea05c6b.js:2:1171898)
    at bs (vendor.049af5c1d008aea05c6b.js:2:3666048)
componentDidCatch @ app.ca0591fe36ffc3c5e8fa.js:1
```

**Desktop (please complete the following information):**
Opera GX browser, windows, wallet.bitshares.org

**Comment by ihorml** [comment]
@grctest hey there! Unfortunately, I can't reproduce it... I'll try to take a look what's going on by your trace

**Comment by ihorml** [comment]
Unfortunately, I can't see the possible issues with the trace. If you can reproduce let me know
