### ISSUE TITLE
TypeError when Navigating to Market from Account Dashboard

### ISSUE THREAD

**Issue by startailcoon** [bitshares/bitshares-ui#837]
I've noticed an issue in the latest wallet (could be unrelated though) where you navigate to a market from the Dashboard with the `Market` icon.

The market then doesn't load.

```
Uncaught (in promise) Error: Feed price assets and call price assets must be the same
    at new e (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:23:70201)
    at file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:110470
    at Array.map (native)
    at t.value (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:110268)
    at t.value (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:110771)
    at h._renderValidatedComponentWithoutOwnerOrContext (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:354631)
    at h._renderValidatedComponent (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:354758)
    at h.performInitialMount (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:350599)
    at h.mountComponent (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:50:349645)
    at Object.mountComponent (file:///C:/Users/start/AppData/Local/Programs/BitShares2-light/resources/app.asar/build/electron/app.js:29:151770)
app.js:55 Uncaught TypeError: Cannot read property '_currentElement' of null
    at h._updateRenderedComponent (app.js:50)
    at h._performComponentUpdate (app.js:50)
    at h.updateComponent (app.js:50)
    at h.receiveComponent (app.js:50)
    at Object.receiveComponent (app.js:29)
    at Object.updateChildren (app.js:50)
    at m._reconcilerUpdateChildren (app.js:50)
    at m._updateChildren (app.js:50)
    at m.updateChildren (app.js:50)
    at m._updateDOMChildren (app.js:50)
```

I haven't investigate further yet, but wanted to document the issue for reference.

**Comment by svk31** [comment]
This commit probably fixed this: https://github.com/bitshares/bitshares-ui/commit/699d6e711383a6034e81aad0b463c9e2dc36a4db
